### ISSUE TITLE
Unable to retrieve game name, each recording defaults to Manual Recording

### ISSUE THREAD

**Issue by RubiksCubei** [padiix/RecORDER#14]
**Describe the bug**
Unable to retrieve game name, each recording defaults to Manual Recording

**To Reproduce**
1.Launch the game, e.g., God of War, PUBG
2.Use OBS hotkey to capture the game source
3.Start video recording
4.Save the video recording

**Expected behavior**
The recorded video file name should change according to the game being played, such as God of War or PUBG.

**Screenshots**
![image](https://github.com/user-attachments/assets/ffdc6be5-6088-4d49-86da-9b9a422fb67d)

**Desktop (please complete the following information):**
Windows 11 23H2
OBS 30.2.3
RecORDER 1.4.2

**Additional context**
[RecORDER.py] ------------------------------
[RecORDER.py] Recording has started...
[RecORDER.py] 
[RecORDER.py] Reloading the signals!
[RecORDER.py] 
[RecORDER.py] Signals reloaded!
[RecORDER.py] 
[RecORDER.py] Reseting the recording related values...
[RecORDER.py] 
[RecORDER.py] ------------------------------
[RecORDER.py] Recording started: Yes
[RecORDER.py] Current recording is None
[RecORDER.py] Current game title: Manual Recording
[RecORDER.py] ------------------------------
[RecORDER.py] ------------------------------
[RecORDER.py] Refreshing sourceUUID...
[RecORDER.py] Recording has stopped, moving the last file into right folder...
[RecORDER.py] Running get_hooked procedure to get current app title...
[RecORDER.py] Source UUID is empty. Defaulting to 'Manual Recording'
[RecORDER.py] Job's done. The file was moved.
[RecORDER.py] ------------------------------
[RecORDER.py] Recording: 2024-09-15 00-51-03.mp4
[RecORDER.py] New path: D:/Action!/OBS\Manual Recording\Manual Recording - 2024-09-15 00-51-03.mp4
[RecORDER.py] ------------------------------

**Comment by padiix** [comment]
Hello there!
It seems you have **not selected the "Capturing source name"** with the source that you use to capture the screen/game.

> The script uses it to correctly determine what it should use to get the title.

I plan to make this done automatically, but I didn't really had the time to check the possible way of doing that, because I was trying to fix other issues I saw with my script.
It's on my priority list, because I can imagine it being annoying to do so when having multiple scenes/scenes collections.

Let me know if that fixed your issue!

**Comment by RubiksCubei** [comment]
Since I use the Advanced Scene Switcher, OBS will automatically switch to the game's scene and capture its source as soon as it detects the specific game's .exe running, and it also automatically enables the replay buffer. This way, the recording process becomes fully automated because I often forget to use the OBS hotkey to capture the game source.


![image](https://github.com/user-attachments/assets/73bfc1b1-22d1-45b9-93e3-851808a85b0d)
![image](https://github.com/user-attachments/assets/12ac45cb-dc25-4f09-a76b-9ce4c96c507d)
Sorry, I can only provide screenshots in Chinese, so I'll describe the effect briefly in text. I hope my explanation is clear and understandable.

As shown in the screenshot, I created an L4D2 game source within the L4D2 scene and set it to only capture the L4D2 game window. Then, using the Advanced Scene Switcher, I set it to switch to the L4D2 scene and enable the replay buffer when it detects the left4dead2.exe process running.

Because I use a large number of game scenes and game sources, I cannot specify RecORDER to capture only a single game source.

**Comment by padiix** [comment]
Ah, I do understand what you mean by that, but sadly I didn't yet figure out a reliable way to help automatically pick the sources based on the hook status, so for now I can say, that the **RecORDER script** is unable to help you organize your files, since it does operate on assumption of manual source selection.

**I will keep you in mind in the following days and I'll try to figure it out asap, so if you don't mind waiting some time, I'll see what I can do.**

On the side note: That's a very cool set-up you have there, I will probably try to figure something similar to yours, since I also have times where I forget to click recording 😄

**Comment by RubiksCubei** [comment]
Sorry, my English isn’t very good, so I used GPT to help me translate into English. There might be some text that doesn't fully convey what I intended, and I hope you understand.

Thank you very much for trying to solve my problem.

I hope it’s not too rude, but I don’t mean any offense; I’m just providing what I think might help.

Could you consider trying features similar to those in the [OBS Recordings Organizer plugin](https://github.com/francdv23/OBS-Recordings-Organizer)? However, I found that plugin has significant issues. For example:
1. When recording L4D2, it automatically creates a folder named "Left 4 Dead 2 - Direct3D 9," but I would prefer the folder name to be just "Left 4 Dead 2."
2. Due to certain circumstances, the game name suffix it retrieves might have trailing spaces, causing the folder name to end with a space. Windows doesn’t allow folders to end with spaces, which causes errors and prevents it from moving the recorded videos into the appropriate folders, resulting in error messages.

**Comment by padiix** [comment]
> Sorry, my English isn’t very good, so I used GPT to help me translate into English. There might be some text that doesn't fully convey what I intended, and I hope you understand.

That's okay, you don't need to worry about such stuff, because I was not offended at all.

>Could you consider trying features similar to those in the [OBS Recordings Organizer plugin](https://github.com/francdv23/OBS-Recordings-Organizer)? However, I found that plugin has significant issues.
Actually, my first step to creating the **RecORDER** was to make the **OBS Recordings Organizer** script working again. 

You can find the working version that I managed to improve a bit [here](https://obsproject.com/forum/resources/obs-recording-organizer-upgraded.1921/) or [here](https://github.com/padiix/OBS-Recordings-Organizer), it should work as you would have wanted, but beware that I will not update it, since I want to focus on RecORDER.

But the **main issue** I had with it is that it used **the external python libraries** for making it work, where there are people not really knowing to much technical stuff about the Python and all. 

So I went and coded a script that is easy to install and use for everyone. It might not yet be where I want it to be, but hopefully soon it will happen

**Comment by padiix** [comment]
I found something promising in terms of what I wanted to achieve to get rid of the manual selection, so I will start working on it soonish.

**Comment by padiix** [comment]
It's very promising, although the way I got it working is not really making me feel good, because it required some static code with names...
But I guess it's fitting as most people wouldn't change the sources name, but I'll keep in mind to put some information in readme after confirming this to be working.

![image](https://github.com/user-attachments/assets/2db939d5-e57a-48da-898a-9cbea5954e45)


```
[RecORDER.py] Checking available sources for a match with source table...
[RecORDER.py] MATCH!
[RecORDER.py] sourceUUID: c027409c-8a83-4222-bbd0-00879de38a59
[RecORDER.py] Fetching the signal handler from the matching source...
[RecORDER.py] Connecting the source signal handler to 'hooked' signal...
[RecORDER.py] Updated the settings!
[RecORDER.py] Fetching data from calldata...
[RecORDER.py] gameTitle: RecORDER.py - OBS-Recorganizer - Python - Visual Studio Code
```

**Comment by padiix** [comment]
Your issue is now fixed in the version [1.4.3](https://github.com/padiix/RecORDER/releases/tag/1.4.3)

Let me know if you face any new issues!

**Comment by RubiksCubei** [comment]
Hello, how should I use it? I just tried version 1.4.3, and I found that it behaves the same as version 1.4.2. There's no difference. Did I miss some settings?

**Comment by padiix** [comment]
Could you show me what you see?
It's a bit hard to understand what's the problem without any logs...

**Comment by padiix** [comment]
Because in the #15 you can see my logs containing the script logs.

The script screen should look like this now:
![image](https://github.com/user-attachments/assets/8f18990d-3a4b-47c1-9efd-4a8cbd8556ef)

**Comment by RubiksCubei** [comment]
When I was playing PUBG, I used the "Default Game Source" within my custom "Default Scene." This game source can only capture the image using the OBS hotkey, as I haven't set up an automatic switch for the PUBG game source yet. However, the saved video file is still named "Manual Recording" and hasn't been renamed to "TslGame" as shown in Task Manager or "PUBG: BATTLEGROUNDS" as displayed in the system taskbar.

log:
[RecORDER.py] Recording has started...
[RecORDER.py] 
[RecORDER.py] Reloading the signals!
[RecORDER.py] Checking available sources for a match with source table...
[RecORDER.py] Nothing was found... Did you name your source in different way than in the 'source' array?
[RecORDER.py] Signals reloaded!
[RecORDER.py] 
[RecORDER.py] Reseting the recording related values...
[RecORDER.py] ------------------------------
[RecORDER.py] Recording started: Yes
[RecORDER.py] Current game title: Manual Recording
[RecORDER.py] ------------------------------
[RecORDER.py] ------------------------------
[RecORDER.py] Recording has stopped, moving the last file into right folder...
[RecORDER.py] Running get_hooked procedure to get current app title...
[RecORDER.py] Source UUID is empty. Defaulting to 'Manual Recording'
[RecORDER.py] Job's done. The file was moved.
[RecORDER.py] ------------------------------
[RecORDER.py] Recording: 2024-09-15 21-03-26.mp4
[RecORDER.py] New path: D:\Action!\OBS\Manual Recording\Manual Recording - 2024-09-15 21-03-26.mp4
[RecORDER.py] ------------------------------
[RecORDER.py] ------------------------------
[RecORDER.py] Replay active? No
[RecORDER.py] ------------------------------
[RecORDER.py] ------------------------------
[RecORDER.py] Replay buffer has started...
[RecORDER.py] 
[RecORDER.py] Reloading the signals!
[RecORDER.py] Checking available sources for a match with source table...
[RecORDER.py] Nothing was found... Did you name your source in different way than in the 'source' array?
[RecORDER.py] Signals reloaded!
[RecORDER.py] 
[RecORDER.py] Reseting the recording related values...
[RecORDER.py] 
[RecORDER.py] ------------------------------
[RecORDER.py] Replay active? Yes
[RecORDER.py] CurrentRecording is None
[RecORDER.py] Game title set to Manual Recording
[RecORDER.py] ------------------------------

**Comment by RubiksCubei** [comment]
Just now, I tried recording L4D2 using the automatic switch I set up for L4D2. However, the recording is still named "Manual Recording."

log:

[RecORDER.py] ------------------------------
[RecORDER.py] Recording has started...
[RecORDER.py] 
[RecORDER.py] Reloading the signals!
[RecORDER.py] Checking available sources for a match with source table...
[RecORDER.py] Nothing was found... Did you name your source in different way than in the 'source' array?
[RecORDER.py] Signals reloaded!
[RecORDER.py] 
[RecORDER.py] Reseting the recording related values...
[RecORDER.py] ------------------------------
[RecORDER.py] Recording started: Yes
[RecORDER.py] Current game title: Manual Recording
[RecORDER.py] ------------------------------
[RecORDER.py] ------------------------------
[RecORDER.py] Recording has stopped, moving the last file into right folder...
[RecORDER.py] Running get_hooked procedure to get current app title...
[RecORDER.py] Source UUID is empty. Defaulting to 'Manual Recording'
[RecORDER.py] Job's done. The file was moved.
[RecORDER.py] ------------------------------
[RecORDER.py] Recording: 2024-09-16 00-37-15.mp4
[RecORDER.py] New path: D:\Action!\OBS\Manual Recording\Manual Recording - 2024-09-16 00-37-15.mp4
[RecORDER.py] ------------------------------

**Comment by RubiksCubei** [comment]
I think I understand what caused the issue now. Since I’m a Chinese user, my game source is named "求生之路2游戏源" instead of "Game Capture," so it couldn’t be recognized. When I deleted the game source I previously created and made a new one named "Game Capture," it started working normally.

However, this leads to another problem. OBS only allows one "Game Capture" source, and if the same source is used across different scenes, the automatic game capture I mentioned earlier doesn’t work as intended. For example, if I set up a "Game Capture" source in the PUBG scene and then add another "Game Capture" source in the L4D2 scene, they are linked. Changing the "Game Capture" source in the L4D2 scene to capture the L4D2 game will also cause the "Game Capture" source in the PUBG scene to switch to capturing L4D2.

**Comment by padiix** [comment]
Alright, so here's what you can do - please edit my script using the highlighted button:
![image](https://github.com/user-attachments/assets/dd309752-52df-4971-a5b4-40b00a31c850)

It should open the window where you can find an array called "sourceNames"
![image](https://github.com/user-attachments/assets/7e77834f-54f1-457a-913b-00d444130c51)


Because your source for capturing the screen/window are localized, I cannot really assume on what are they going to be called, so I made the script as easy for anybody to edit as possible.

As long as the names you will put in the highlighted part will be the same names as the sources in your workflow it should always work

Just make sure that you are keeping the syntax correct:
Example:
![image](https://github.com/user-attachments/assets/30f09107-0e7a-4df6-904f-18f226a13785)


I wish there was a better way of doing it, but there is nothing really I could do without using the 3rd party stuff, which is not really what I am going with my script here.

Let me know if you have any more questions!

**Comment by RubiksCubei** [comment]
Okay, thank you, I know what to do now.

**Comment by padiix** [comment]
> Okay, thank you, I know what to do now.

No problem, if you do not mind I will close the issue and send an hotfixed 1.4.2 version to avoid the issue for other users as well as make a part of README about doing what I instructed you to do so.
