### ISSUE TITLE
Recording not moving into correct folders.

### ISSUE THREAD

**Issue by PixlPixi** [padiix/RecORDER#23]
Was told to use this Github page to report any future issues so I apologize if this isn't the correct way to go about reporting this issue. I'm having trouble getting the files to move into the appropriate folders and when I look at the script log it seems that my issue is related to the new asynchronous file handling update.

AttributeError: module 'asyncio' has no attribute 'run'

This is the message that's I'm getting the script log. I've updated from from 1.3.4 after seeing that my feature request for the screenshot organizing was implemented. Added the names of my sources so they would be recognized by the script and everything so far is working just as before, with the exception that files aren't being moved.

Probably something on my end, but I'm not sure what the issue is. I've updated OBS, completely uninstalled the old version of RecORDER.py and setup the file paths in the script settings to point to the recordings directory. Not sure what else I can try.

**Comment by PixlPixi** [comment]
Issue was fixed by updated Python. Was under the impression that only Python 3.6 worked with OBS, but I guess that was changed at some point as updating to Python 3.11 solved the issue.

**Comment by padiix** [comment]
Hello there @PixlPixi,

I just saw your issue and let me add some things to this:
- The recommended version for my script was always **3.11**. It's not a problem that you used different once, because maybe other scripts that you use need this specific version. In the next version that's coming soonish, I will place a warning once user uses my script with Python lower than the **3.11**
- Make sure (after installing the newer version of Python and applying it to the OBS) to re-apply the script as well, because it can cause some unexpected issues that I have no way of knowing.

Also big thanks for heeding my advice, I know making new accounts is pain, but that way let's me connect issues with commits, so I can have everything documented.

**Comment by PixlPixi** [comment]
Everything is working exactly as intended now. I don't use Python scripts for anything else in OBS. Just LUA scripts. So it's no issue using a newer version. I just recall a possibly outdated tutorial I watched said that OBS doesn't support Python beyond 3.6 but who knows when that was accurate.

Also I don't mind using Github. I already had an account I just never use it.
